#!/usr/bin/pyton3
raise_exception_msg(message=""):
    raise NameError(message)
